apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb          # Nome novo para não conflitar com o original
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    # Estes seletores buscam os pods do Prometheus já existentes.
    # No kube-prometheus-stack padrão, geralmente é este:
    app.kubernetes.io/name: prometheus
  ports:
    - protocol: TCP
      port: 33001           # A porta externa que você quer usar na rede
      targetPort: 9090      # A porta interna onde o Prometheus roda