apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: giropops-senhas-canary
  annotations: # Configura o rewrite da URL   
    nginx.ingress.kubernetes.io/rewrite-target: /

    nginx.ingress.kubernetes.io/canary: "true" # Habilita o suporte a canary releases
    nginx.ingress.kubernetes.io/canary-weight: "10" # Define o peso do tráfego para o canary (10%)

    cert-manager.io/cluster-issuer: "selfsigned-issuer" # Anotação para o cert-manager usar o ClusterIssuer autoassinado
    #cert-manager.io/cluster-issuer: "letsencrypt-prod" # Anotação para o cert-manager usar o ClusterIssuer correto
spec:
  ingressClassName: nginx #inseri a classe do ingress, pois nao funcionou sem. 
  tls:
  - hosts:
    - giropops.nginx.io
    secretName: giropops-senhas-tls # Nome do segredo TLS onde o certificado será armazenado
  rules:
  - host: giropops.nginx.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: nginx
            port:
              number: 80